version: '3'
services:
    web:
        build: .
        ports: 
            - "3000:3000"
        volumes:
            - ./:/app
        depends_on:
            - "mongo"
    mongo:
        image: "mongo"
        ports: 
            - "27017:27017"
    adminmongo:
        image: "mrvautin/adminmongo"
        ports: 
            - "1234:1234"
        environment:
            - "HOST=0.0.0.0"