version: '3'
services:
    web:
        container_name: "express"
        build: .
        ports: 
            - "3000:3000"
        volumes:
            - ./:/app
        depends_on:
            - "mongo"
    mongo:
        container_name: "mongos"
        image: "mongo"
        command: "mongos --configdb cfrepl/192.168.100.16:40001,192.168.100.16:40002,192.168.100.16:40003 --bind_ip 0.0.0.0 --port 27017"
        ports: 
            - "27017:27017"
    adminmongo:
        container_name: "adminmongos"
        image: "mrvautin/adminmongo"
        ports: 
            - "1234:1234"
        environment:
            - "HOST=0.0.0.0"